// js/maps/cypriot_map.js

// Ensure the global ALL_SCRIPT_DATA object exists
window.ALL_SCRIPT_DATA = window.ALL_SCRIPT_DATA || {};

window.ALL_SCRIPT_DATA["cypriot"] = {
    description: "Cypriot Syllabary (Phonetic)",
    unicode_range: ['10800', '1083F'], // Store as array or object
    to_latin_map: {
        '\u10800': 'a',    // 𐠀 CYPRIOT SYLLABLE A
        '\u10801': 'e',    // 𐠁 CYPRIOT SYLLABLE E
        '\u10802': 'i',    // 𐠂 CYPRIOT SYLLABLE I
        '\u10803': 'o',    // 𐠃 CYPRIOT SYLLABLE O
        '\u10804': 'u',    // 𐠄 CYPRIOT SYLLABLE U
        '\u10805': 'ja',   // 𐠅 CYPRIOT SYLLABLE JA
        '\u10806': 'je',   // 𐠆 CYPRIOT SYLLABLE JE
        '\u10808': 'ka',   // 𐠈 CYPRIOT SYLLABLE KA
        '\u1080A': 'ke',   // 𐠊 CYPRIOT SYLLABLE KE
        '\u1080B': 'ki',   // 𐠋 CYPRIOT SYLLABLE KI
        '\u1080C': 'ko',   // 𐠌 CYPRIOT SYLLABLE KO
        '\u1080D': 'ku',   // 𐠍 CYPRIOT SYLLABLE KU
        '\u1080E': 'la',   // 𐠎 CYPRIOT SYLLABLE LA
        '\u1080F': 'le',   // 𐠏 CYPRIOT SYLLABLE LE
        '\u10810': 'li',   // 𐠐 CYPRIOT SYLLABLE LI
        '\u10811': 'lo',   // 𐠑 CYPRIOT SYLLABLE LO
        '\u10812': 'lu',   // 𐠒 CYPRIOT SYLLABLE LU
        '\u10813': 'ma',   // 𐠓 CYPRIOT SYLLABLE MA
        '\u10814': 'me',   // 𐠔 CYPRIOT SYLLABLE ME
        '\u10815': 'mi',   // 𐠕 CYPRIOT SYLLABLE MI
        '\u10816': 'mo',   // 𐠖 CYPRIOT SYLLABLE MO
        '\u10817': 'mu',   // 𐠗 CYPRIOT SYLLABLE MU
        '\u10818': 'na',   // 𐠘 CYPRIOT SYLLABLE NA
        '\u10819': 'ne',   // 𐠙 CYPRIOT SYLLABLE NE
        '\u1081A': 'ni',   // 𐠚 CYPRIOT SYLLABLE NI
        '\u1081B': 'no',   // 𐠛 CYPRIOT SYLLABLE NO
        '\u1081C': 'nu',   // 𐠜 CYPRIOT SYLLABLE NU
        '\u1081D': 'xa',   // 𐠝 CYPRIOT SYLLABLE XA
        '\u1081E': 'xe',   // 𐠞 CYPRIOT SYLLABLE XE
        '\u10820': 'xo',   // 𐠠 CYPRIOT SYLLABLE XO
        '\u10822': 'pa',   // 𐠢 CYPRIOT SYLLABLE PA
        '\u10823': 'pe',   // 𐠣 CYPRIOT SYLLABLE PE
        '\u10824': 'pi',   // 𐠤 CYPRIOT SYLLABLE PI
        '\u10825': 'po',   // 𐠥 CYPRIOT SYLLABLE PO
        '\u10826': 'pu',   // 𐠦 CYPRIOT SYLLABLE PU
        '\u10827': 'ra',   // 𐠧 CYPRIOT SYLLABLE RA
        '\u10828': 're',   // 𐠨 CYPRIOT SYLLABLE RE
        '\u10829': 'ri',   // 𐠩 CYPRIOT SYLLABLE RI
        '\u1082A': 'ro',   // 𐠪 CYPRIOT SYLLABLE RO
        '\u1082B': 'ru',   // 𐠫 CYPRIOT SYLLABLE RU
        '\u1082C': 'sa',   // 𐠬 CYPRIOT SYLLABLE SA
        '\u1082D': 'se',   // 𐠭 CYPRIOT SYLLABLE SE
        '\u1082E': 'si',   // 𐠮 CYPRIOT SYLLABLE SI
        '\u1082F': 'so',   // 𐠯 CYPRIOT SYLLABLE SO
        '\u10830': 'su',   // 𐠰 CYPRIOT SYLLABLE SU
        '\u10831': 'ta',   // 𐠱 CYPRIOT SYLLABLE TA
        '\u10832': 'te',   // 𐠲 CYPRIOT SYLLABLE TE
        '\u10833': 'ti',   // 𐠳 CYPRIOT SYLLABLE TI
        '\u10834': 'to',   // 𐠴 CYPRIOT SYLLABLE TO
        '\u10835': 'tu',   // 𐠵 CYPRIOT SYLLABLE TU
        '\u10836': 'wa',   // 𐠶 CYPRIOT SYLLABLE WA
        '\u10837': 'we',   // 𐠷 CYPRIOT SYLLABLE WE
        '\u10838': 'wi',   // 𐠸 CYPRIOT SYLLABLE WI
        '\u1083B': 'za',   // 𐠻 CYPRIOT SYLLABLE ZA
        '\u1083F': '.',    // 𐠿 CYPRIOT SYLLABLE PUNCTUATOR
    },
    // FROM_LATIN_MAP will be generated by all_maps_loader.js
};